"""add agent_id column in campaign

Revision ID: dcfdd73eb4b1
Revises: ece37de557a2
Create Date: 2026-08-26 17:53:54.810288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcfdd73eb4b1'
down_revision: Union[str, Sequence[str], None] = 'ece37de557a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('agent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'agent_id')
    # ### end Alembic commands ###
