"""add_tags_extracted_columns_in_calls

Revision ID: ece37de557a2
Revises: c13decd99463
Create Date: 2026-08-26 12:01:11.006723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece37de557a2'
down_revision: Union[str, Sequence[str], None] = 'c13decd99463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('extracted_data', sa.JSON(), nullable=False))
    op.add_column('calls', sa.Column('tags', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'tags')
    op.drop_column('calls', 'extracted_data')
    # ### end Alembic commands ###
